# Starts the backend with a filewatcher monitoring local source files
# and livereload on file change

version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: node_modules/.bin/nodemon --watch src --exec 'ts-node' src/entry/web.debug
    volumes:
      - .:/app
