version: "3"

services:
  db:
    image: mdillon/postgis

  web:
    tty: true
    stdin_open: true
    command: /bin/bash -c "node build/src/entry/release && node build/src/entry/web.production"
    build: .
    environment:
      - PORT=8000
      - DATABASE_URL=postgres://postgres@db/postgres
      - LOG_LEVEL=debug
    ports:
      - 8000:8000
    depends_on:
      - db
