version: "3"

services:
  db:
    image: mdillon/postgis

  web:
    tty: true
    stdin_open: true
    build: .
    environment:
      - PORT=8000
      - DATABASE_URL=postgres://postgres@db/postgres
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: node_modules/.bin/nodemon --watch src src/entry/web.debug
    depends_on:
      - db
