# Starts the backend with a filewatcher monitoring local source files
# and livereload on file change

version: "3"

services:
  db:
    image: mdillon/postgis
    ports:
      - 5432:5432

  web:
    build:
      context: ../..
      dockerfile: backend/docker/backend.dev.dockerfile
    command: node_modules/.bin/nodemon --watch backend --watch common --exec yarn start backend web.debug
    volumes:
      - ../..:/app
    environment:
      - BACKEND_URL=http://localhost:8000
