version: "3"

services:
  amqp:
    image: rabbitmq

  s3-test:
    image: lphoward/fake-s3

  db:
    image: mdillon/postgis
    ports:
      - 5432:5432

  web:
    tty: true
    stdin_open: true
    command: /bin/bash -c "yarn start backend release && yarn start backend web.production"
    build:
      context: ../..
      dockerfile: backend/docker/backend.dockerfile
    environment:
      - PORT=8000
      - CLOUDAMQP_URL=amqp://amqp
      - DATABASE_URL=postgres://postgres@db/postgres
      - LOG_LEVEL=debug
      - BUCKETEER_AWS_ACCESS_KEY_ID=BUCKETEER_AWS_ACCESS_KEY_ID
      - BUCKETEER_AWS_REGION=test
      - BUCKETEER_AWS_SECRET_ACCESS_KEY=BUCKETEER_AWS_SECRET_ACCESS_KEY
      - BUCKETEER_BUCKET_NAME=BUCKETEER_BUCKET_NAME
      - AWS_ENDPOINT=http://{service}-{region}:4569
    ports:
      - 8000:8000
    depends_on:
      - db
      - s3-test
      - amqp
